### ISSUE TITLE
SBG_TIME_OUT

### ISSUE THREAD

**Issue by zhangjc163** [SBG-Systems/sbg_ros_driver#24]
hello, I used the ig500N，and your ros driver,but it did not word. and the waring is rrror:SBG_TIME_OUT. what the meaning?

**Comment by ErwanCL** [comment]
Hello,
The IG500N is an outdated product for years now. It used an old communication protocol, so it is not useable with this driver.
Depending on your application, I recommend you to check for a product update.

Best regards
