### ISSUE TITLE
TF broadcaster

### ISSUE THREAD

**Issue by KevinBdn** [SBG-Systems/sbg_ros_driver#29]
Hi, 

Would it be possible to add a Transform broadcaster message between a "base_link" and the SBG unit ?

Best,

**Comment by ErwanCL** [comment]
Hello,

From the documentation page (http://wiki.ros.org/tf2), I understood that TF broadcasting is meant to publish the frame coordinate in a local NED system.
So for the SBG unit, using inertial data, it is possible to compute the coordinates X,Y,Z, considering a reference point with local latitude and longitude (Used to convert the  navigation data latitude, longitude of the IMU).
If you want TF to works, I guess your "base_link" should be able to compute its local position as well.

Is that what you're looking for ?

Regards
