### ISSUE TITLE
Regarding RPY problems

### ISSUE THREAD

**Issue by YushengWHU** [SBG-Systems/sbg_ros_driver#39]
Hello here, it might be a stupid but long question.
I am currently using  a ellipse 2N and a lidar with my lidar frame ( **forward-left-up**) , in order to have them aligned together, I set the ellipse 2N frame also to **forward-left-up** in sbg-center, then I followed a [video](https://youtu.be/BOUK8LYQhHs) to debug my IMU with lidar.
I subscribed my IMU topic, and try aligning the two coordinates together using below
```
        // rotate acceleration
        Eigen::Vector3d acc(imu_in.linear_acceleration.x, imu_in.linear_acceleration.y, imu_in.linear_acceleration.z);
        acc = extRot * acc;
        imu_out.linear_acceleration.x = acc.x();
        imu_out.linear_acceleration.y = acc.y();
        imu_out.linear_acceleration.z = acc.z();
        // rotate gyroscope
        Eigen::Vector3d gyr(imu_in.angular_velocity.x, imu_in.angular_velocity.y, imu_in.angular_velocity.z);
        gyr = extRot * gyr;
        imu_out.angular_velocity.x = gyr.x();
        imu_out.angular_velocity.y = gyr.y();
        imu_out.angular_velocity.z = gyr.z();
        // rotate roll pitch yaw
        Eigen::Quaterniond q_from(imu_in.orientation.w, imu_in.orientation.x, imu_in.orientation.y, imu_in.orientation.z);
        Eigen::Quaterniond q_final = q_from * extQRPY;
        imu_out.orientation.x = q_final.x();
        imu_out.orientation.y = q_final.y();
        imu_out.orientation.z = q_final.z();
        imu_out.orientation.w = q_final.w();
```
As my pre-set IMU coordinate is the same with lidar, thus the rotation matrix below should solve the problem (As with most of my IMU)
```
  extrinsicRot: [1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
  extrinsicRPY: [1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
```
When I put it still on the ground, the output gives me
```
IMU acc: 
x: 0.0549914, y: -0.0458053, z: 9.80859
IMU gyro: 
x: -0.00148256, y: -0.00329256, z: 0.00248773
IMU roll pitch yaw: 
roll: 3.13729, pitch: 0.00645817, yaw: -1.54013
```
The IMU acc and gyro satisfy the assumption,which means the **extrinsicRot** is right. However, as you notice, the roll should be around zero instead around pi. 

1. Besides, accroding to **forward-left-up** frame, when I rotate the ellipse2N counter-clockwise on the ground (thus clockwise for **up** ) the yaw should increase, but for my case here, the yaw decreases. 
2. Meanwhile, when I push down the head of ellipse2N (which means clockwise for **left**), the pitch should increase, but also decreases.

Noticing that, I tried to play a bit with **extrinsicRPY** , no matter how I change the parameters, the 1 and 2 problem still exists, for example, below is a trial with outputs.
```
  extrinsicRPY: [1, 0, 0,
                   0, -1, 0,
                   0, 0, -1]
```
Output of RPY
```
IMU roll pitch yaw: 
roll: -0.0271597, pitch: -0.0412392, yaw: -0.845946
```
Do you have any suggestions? Thanks

**Comment by rsiryani** [comment]
Hi,

We have recently updated the ROS driver implementation to support both NED and ENU output frame conventions.
Our INS are using NED convention but ROS is using ENU.

I would recommend you check the latest driver version and have a look at the updated README:
[https://github.com/SBG-Systems/sbg_ros_driver#change-frame-parameters]

Please let me know if it has fixed your issue.

Thanks,
