### ISSUE TITLE
Update sbgECom Library version to latest Release?

### ISSUE THREAD

**Issue by thealanjason** [SBG-Systems/sbg_ros_driver#40]
Could the Ros driver be updated to use the latest release of the sbgECom library?
I am particularly interested in using the Velocity in the vehicle's frame(not NED) as well as the Slip Values from sbgEComBinaryLogAutomotiveData

**Comment by rsiryani** [comment]
Hi and thank you for your request.

Up to now, both the body velocity and automotive outputs are available only over a CAN bus.

However, we are planning to include these outputs in our next firmware planned for end of Q1 2021.

Thank you for your understanding and also please not that the ROS driver is able to generate a body velocity from the NED velocity on the fly as soon as you also output the INS attitude.

As for the Slip value is concerned, please get back to our support team support@sbg-systems.com so they can explain how to compute it by yourself.

It's a very easy and straightforward computation.

Kind Regards,
