### ISSUE TITLE
Update SbgEkfNav & SbgEkfGpsPos position from Vector3 to float64 LLA

### ISSUE THREAD

**Issue by rsiryani** [SBG-Systems/sbg_ros_driver#60]
to correctly address this issue, we should update the following messages def:
- SbgEkfNav.msg
- SbgEkfGpsPos.msg

We should replace position geometry_msgs/Vector3 to three members that are latitude/longitude/altitude

**Comment by mzembsbg** [comment]
Integrated in PR #62
