### ISSUE TITLE
Package: ros-noetic-sbg-driver not in the ROS directory.

### ISSUE THREAD

**Issue by ghost** [SBG-Systems/sbg_ros_driver#72]
Package `ros-noetic-sbg-driver` can not be installed by command
`sudo apt-get install ros-noetic-sbg-driver`

**Comment by mzembsbg** [comment]
Hi.

Can you give the exact output of your command ? (I suppose something like package not found, but just to be sure).

We are currently having issues with the ROS release system for noetic.
In the mean time I suggest that you build from sources as described here:
https://github.com/SBG-Systems/sbg_ros_driver#building-from-sources

**Comment by DmsPaleBlue** [comment]
Yep, something like package not found.

**Comment by richardbraun** [comment]
The package is currently available, closing the issue.
