### ISSUE TITLE
RINEX Data from /sbg/gps_raw

### ISSUE THREAD

**Issue by nuneslu** [SBG-Systems/sbg_ros_driver#82]
Hi, we have been trying to get the raw data from the SBG GPS to post-process and get an accurate position. We saw this closed [issue](https://github.com/SBG-Systems/sbg_ros_driver/issues/43) and tried to dump the raw data from the ros topic to a bin file, but we could not convert it (we have used the RTKLib to convert it). We would like to know if there is any intermediary step to get the RINEX data from the GPS.

**Comment by tolesam** [comment]
@nuneslu 
Thank you for your feedback.
The following comment should answer to your question https://github.com/SBG-Systems/sbg_ros_driver/issues/43#issuecomment-1328791167
