### ISSUE TITLE
Frame of 'sbg/SbgGpsPos'

### ISSUE THREAD

**Issue by louis-wiesmann** [SBG-Systems/sbg_ros_driver#91]
Hey, i have a question regarding the coordinate frame of the SbgGpsPos. Is it:

1. in the frame of the imu (so the specified lever arm calibration parameters already applied) or 
2. rather in the frame of the gps (without applying the offset to the imu). 

Another Question: Is the SbgGpsPos filtered in anyway (some EKF output), or the raw positions.

Best, 
Louis

**Comment by rsiryani** [comment]
Hi,

The SbgGpsPos, is the real time PVT output from the GNSS and as such is located at the GNSS primary antenna.
It is thus not affected by any lever arm nor filtered by the EKF filter.

Only the GNSS antenna model might affect the height component but only for High Performence INS such as EKINOX/APOGEE/QUANTA/NAVSIGHT

Hope it helps,
